---

- name: "(01) Subscribe the host to RHSM"
  block:
    - name: Check Pool ID definition
      fail: msg="Extra variable rhn_poolid has not been defined. Please add it before running this playbook"
      when: rhn_poolid is not defined

    - name: Subscribe the host
      redhat_subscription:
        state: present
        username: "{{ rhn_username }}"
        password: "{{ rhn_password }}"
        autosubscribe: true

    - name: Attach to pool
      command: subscription-manager attach --pool="{{ rhn_poolid }}"
      ignore_errors: yes
  when: rhsm_subscribe_host|bool