---

- name: "(02) install EPEL repository"
  block:
    - name: Download EPEL for RHEL
      get_url:
        url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
        dest: "/tmp"
      tags:
        - common

    - name: Install EPEL for RHEL
      action: "{{ ansible_pkg_mgr }} name=/tmp/epel-release-latest-7.noarch.rpm state=present"
      changed_when: False
      tags:
        - common

- name: "(02) install {{ jvm_pkg_name }}"
  action: "{{ ansible_pkg_mgr }} name={{ jvm_pkg_name }} state=latest"
  when: config.install_java|bool
  tags:
  - common

- name: "(02) install packages"
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=latest"
  with_items:
    - unzip
    - nmap
    - git
    - lsof
    - telnet
    - bash-completion
    - bash-completion-extras
    - vim
  tags:
  - common
 
- name: "(02) upgrade all packages"
  yum:
    name: '*'
    state: latest

- firewalld:
    port: 9990/tcp
    permanent: true
    state: enabled
  when: jboss.host_type == "master"

- firewalld:
    port: 9999/tcp
    permanent: true
    state: enabled
  when: jboss.host_type == "master"
  
- firewalld:
    port: 8080/tcp
    permanent: true
    state: enabled

- firewalld:
    port: 8443/tcp
    permanent: true
    state: enabled

- name: "(02) bounce firewalld"
  service: name=firewalld state=restarted