---

- name: "(02) install EPEL repository"
  block:
    - name: Download EPEL for RHEL
      get_url:
        url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
        dest: "/tmp"
      tags:
        - common

    - name: Install EPEL for RHEL
      action: "{{ ansible_pkg_mgr }} name=/tmp/epel-release-latest-7.noarch.rpm state=present"
      changed_when: False
      tags:
        - common

- name: "(02) install {{ jvm_pkg_name }}"
  action: "{{ ansible_pkg_mgr }} name={{ jvm_pkg_name }} state=latest"
  when: config.install_java|bool
  tags:
  - common

- name: "(02) install packages"
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=latest"
  with_items:
    - unzip
    - nmap
    - git
    - lsof
    - telnet
    - bash-completion
    - bash-completion-extras
    - vim
  tags:
  - common
 
- name: "(02) upgrade all packages"
  yum:
    name: '*'
    state: latest

# for udp multicast and service management, all the following ports must be opened:
# 8080/tcp 8443/tcp 9990/tcp 9999/tcp 45700/udp 55200/udp 45688/udp 23364/udp 7600/tcp
# in case you need static-discovery based on TCPPING, you'll need to open additional ports.

- firewalld:
    port: 9990/tcp
    permanent: true
    state: enabled
  when: jboss.host_type == "master"

- firewalld:
    port: 9999/tcp
    permanent: true
    state: enabled
  when: jboss.host_type == "master"
  
- firewalld:
    port: 8080/tcp
    permanent: true
    state: enabled

- firewalld:
    port: 8443/tcp
    permanent: true
    state: enabled

- firewalld:
    port: 45700/udp
    permanent: true
    state: enabled
  when: jboss.host_type == "slave"

- firewalld:
    port: 55200/udp
    permanent: true
    state: enabled
  when: jboss.host_type == "slave"

- firewalld:
    port: 45688/udp
    permanent: true
    state: enabled
  when: jboss.host_type == "slave"

- firewalld:
    port: 23364/udp
    permanent: true
    state: enabled
  when: jboss.host_type == "slave"

- firewalld:
    port: 7600/tcp
    permanent: true
    state: enabled
  when: jboss.host_type == "slave"

- firewalld:
    source: 230.0.0.4/24
    permanent: true
    state: enabled
  when: jboss.host_type == "slave"

- name: "(02) bounce firewalld"
  service: name=firewalld state=restarted