---

- name: "(02) install EPEL repository"
  block:
    - name: Download EPEL for RHEL
      get_url:
        url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
        dest: "/tmp"
      tags:
        - preinstall

    - name: Install EPEL for RHEL
      action: "{{ ansible_pkg_mgr }} name=/tmp/epel-release-latest-7.noarch.rpm state=present"
      changed_when: "False"
      tags:
        - preinstall

- name: "(02) install {{ jvm_pkg_name }}"
  action: "{{ ansible_pkg_mgr }} name={{ jvm_pkg_name }} state=latest"
  when: config.install_java|bool
  tags:
  - preinstall

- name: "(02) install packages"
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=latest"
  with_items:
    - unzip
    - nmap
    - git
    - lsof
    - telnet
    - bash-completion
    - bash-completion-extras
    - vim
  tags:
    - preinstall

- name: "(02) upgrade all packages"
  yum:
    name: '*'
    state: latest
  tags:
    - preinstall