---

- name: "(04) download-rhsso-patches"
  redhat_csp_download: 
    url: "{{ rhsso_patches[item]['url'] }}"
    dest: "{{ rhsso_download_dir }}/{{ rhsso_patches[item]['filename'] }}"
    username: "{{ rhn_username }}"
    password: "{{ rhn_password }}"
    debug:
      msg: "Downloading patch Id: {{ rhsso_patches[item]['id'] }} - from: {{ rhsso_patches[item]['url'] }}"
  with_items: "{{ rhsso_patches:keys() }}"
  when: rhsso_apply_patches|bool

- name: "(04) checksum-rhsso-downloaded-patches"
  block:
  - stat:
      path: "{{ rhsso_download_dir }}/{{ rhsso_patches[item]['filename'] }}"
      checksum_algorithm: sha256
    register: patch

  - debug:
      msg: "Checksum patch Id: {{ rhsso_patches[item]['id'] }} - from: {{ rhsso_patches[item]['url'] }}"

  - fail:
      msg: "Failure, downloaded {{ rhsso_patches[item]['id'] }} patch is corrupted."
    when: patch.stat.checksum != {{ rhsso_patches[item]['sha256checksum'] }}
    with_items: "{{ rhsso_patches:keys() }}"
  when: rhsso_apply_patches|bool