---

- name: "(06) execute cli file(s)"
  become_user: "{{ jboss.user }}"
  shell: 'bash -c "nohup {{ jboss_home }}/bin/standalone.sh -c {{ jboss_eap_instance_standalone_file }} -Djboss.socket.binding.port-offset={{ jboss_eap_instance_port_offset }} -Djboss.management.native.port={{ jboss_eap_instance_cli_default_port }} -Djboss.server.base.dir={{ jboss_eap_instance_dir }} --admin-only & " && sleep 10 && {{ jboss_home }}/bin/jboss-cli.sh -c --controller=127.0.0.1:{{ jboss_eap_instance_cli_port }} --file="{{ jboss_eap_instance_dir }}/configuration/{{ item | basename }}" && pkill -TERM -f "^java(.*){{ jboss_eap_instance_dir }}"'
  with_items: "{{ cli_list }}"
  when: conf_11.changed
  ignore_errors: yes
  register: cli_result

- name: "(06) stop faulty instances"
  when: conf_11.changed and cli_result.failed is defined and cli_result.failed
  become_user: "{{ jboss.user }}"
  ignore_errors: yes
  shell: 'pkill -TERM -f "^java(.*){{ jboss_eap_instance_dir }}"'

- name: "(06) show cli execution failure"
  when: conf_11.changed and cli_result.failed is defined and cli_result.failed
  fail: msg="One of the CLI commands failed."

# /--------------------------------------------------------------------------------\
# | TCP:TCPPING                                                                    |
# \--------------------------------------------------------------------------------/

# cli (./jboss-cli.sh --connect --controller={IP_DOMAIN_CONTROLLER}:9990 --file=../tcp-cluster.cli)

# /--------------------------------------------------------------------------------\
# | ORACLE DBMS URL                                                                |
# \--------------------------------------------------------------------------------/

# cli: /profile=auth-server-clustered/subsystem=datasources/jdbc-driver=oracle:add(driver-module-name=com.oracle, driver-name=oracle)
# cli: /profile=auth-server-clustered/subsystem=datasources/data-source=KeycloakDS:write-attribute(name=connection-url,value="jdbc:oracle:thin:@(DESCRIPTION =
# (ADDRESS = (PROTOCOL = TCP)(HOST = dbms-host.io)(PORT = 1521))
# (CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = dbms-host)))")
# cli: /profile=auth-server-clustered/subsystem=datasources/data-source=KeycloakDS:write-attribute(name=driver-name,value=oracle)
# cli: /profile=auth-server-clustered/subsystem=datasources/data-source=KeycloakDS:write-attribute(name=user-name,value=DBMS-USER)
# cli: /profile=auth-server-clustered/subsystem=datasources/data-source=KeycloakDS:write-attribute(name=password,value=DBMS-PASSWORD)
# cli: /profile=auth-server-clustered/subsystem=datasources/data-source=KeycloakDS:write-attribute(name=min-pool-size,value=5)
# cli: /profile=auth-server-clustered/subsystem=datasources/data-source=KeycloakDS:write-attribute(name=max-pool-size,value=30)
# cli: /profile=auth-server-clustered/subsystem=datasources/data-source=KeycloakDS:write-attribute(name=initial-pool-size,value=5)
# cli: /profile=auth-server-clustered/subsystem=datasources/data-source=KeycloakDS:write-attribute(name=pool-use-strict-min,value=true)
# cli: /profile=auth-server-clustered/subsystem=datasources/data-source=KeycloakDS:write-attribute(name=check-valid-connection-sql,value="select 1 from dual")
# cli: /profile=auth-server-clustered/subsystem=datasources/data-source=KeycloakDS:write-attribute(name=valid-connection-checker-class-name,value=org.jboss.jca.adapters.jdbc.extensions.oracle.OracleValidConnectionChecker)
# cli: /profile=auth-server-clustered/subsystem=datasources/data-source=KeycloakDS:write-attribute(name=background-validation,value=true)
# cli: /profile=auth-server-clustered/subsystem=datasources/data-source=KeycloakDS:write-attribute(name=background-validation-millis,value=600000)
# cli: /profile=auth-server-clustered/subsystem=datasources/data-source=KeycloakDS:write-attribute(name=exception-sorter-class-name,value=org.jboss.jca.adapters.jdbc.extensions.oracle.OracleExceptionSorter)
# cli: /profile=auth-server-clustered/subsystem=datasources/data-source=KeycloakDS:write-attribute(name=stale-connection-checker-class-name,value=org.jboss.jca.adapters.jdbc.extensions.oracle.OracleStaleConnectionChecker)
# cli: :reload-servers(blocking=true)

# /--------------------------------------------------------------------------------\
# | JBOSS EAP LOG HANDLER                                                          |
# \--------------------------------------------------------------------------------/

# > /path=custom.log.dir:add(path=/var/log/jboss/) 
# > /profile=auth-server-clustered/subsystem=logging/periodic-size-rotating-file-handler=PERIODIC_SIZE_ROTATING_SSO:add(append=false,file={relative-to="custom.log.dir",path="sso-server.log"},rotate-size=5000,suffix=".yyyy-MM-dd",autoflush=true,max-backup-index=25,level="INFO",encoding="utf-8",autoflush=true,rotate-on-boot=true)
# > /profile=auth-server-clustered/subsystem=logging/root-logger=ROOT:add-handler(name=PERIODIC_SIZE_ROTATING_SSO)
