---

# /--------------------------------------------------------------------------------\
# | remove downloaded files and scripts                                            |
# \--------------------------------------------------------------------------------/

- name: "(08) delete get-pip.py"
  file: state=absent path=/tmp/get-pip.py
  tags:
    - cleanup

- name: "(08) remove {{ rhsso_artifact_version }} server zip file (free up space from /tmp)"
  file: path="{{ general.download_dir }}/{{ rhsso_artifact_name }}" state=absent
  ignore_errors: true
  when: rhsso_remove_patches_after_install|bool
  tags:
    - cleanup

- name: "(08) flush download dir folder (free up space from /tmp)"
  shell: "/usr/sbin/lsof +L1 {{ general.download_dir }} > /dev/null"
  ignore_errors: true
  when: rhsso_remove_patches_after_install|bool
  tags:
    - cleanup

# /--------------------------------------------------------------------------------\
# | remove server jvm from host-master (recomended)                                |
# \--------------------------------------------------------------------------------/
