---

# /--------------------------------------------------------------------------------\
# | remove downloaded files and scripts                                            |
# \--------------------------------------------------------------------------------/

- name: "(08) delete get-pip.py"
  file: state=absent path=/tmp/get-pip.py

- name: "(08) remove {{ rhsso_artifact_version }} server zip file (free up space from /tmp)"
  shell: "/bin/rm -rf {{ general.download_dir }}/{{ rhsso_artifact_name }}"
  when: rhsso_remove_patches_after_install|bool

- name: "(08) trunk and flush download dir folder (free up space from /tmp)"
  shell: "/usr/sbin/lsof +L1 {{ general.download_dir }} > /dev/null"
  ignore_errors: true
  when: rhsso_remove_patches_after_install|bool
  
# /--------------------------------------------------------------------------------\
# | remove server jvm from host-master (recomended)                                |
# \--------------------------------------------------------------------------------/
