---

- include_vars: rhn_credentials.yml

#### 
#- include: 00__check_required_variables.yml
#  become: true

#### 
#- include: 01__subscribe_rhsm.yml
#  become: true

#### 
#- include: 02__install_dependencies.yml
#  become: true

#### 
#- include: 03__download_and_install.yml
#  become: true

#### 
#- include: 04__download_patches_and_checksum.yml
#  become: true

#### 
- include: 05__apply_patches.yml
  become: true
