---

- set_fact:
    obj: "{{ item }}"
  tags:
    - patches

- name: "(subtask 03) preparing to download patch {{ obj.id }}"
  debug: msg={{ obj }}
  tags:
    - patches

- name: "(subtask 03) checking existence of patch id:{{ obj.id }}"
  become: true
  stat:
    path: "{{ general.download_dir }}/{{ obj.filename }}"
  register: patch_exists
  tags:
    - patches

# extract patch id original checksum
- name: "(subtask 03) acquire red hat single sign-on {{ obj.id }} origin patch checkum facts"
  set_fact:
    patch_checksum: "{{ obj.sha256checksum }}"
  when: patch_exists.stat.exists
  tags:
    - patches

- stat:
    path: "{{ general.download_dir }}/{{ obj.filename }}"
    checksum_algorithm: sha256
  register: checksum_result
  when: patch_exists.stat.exists
  tags:
    - patches

- name: "(subtask 03) deleting patch id:{{ obj.id }} - reason: checksum failed or download corrupted."
  file: path={{ item }} state=absent
  with_items:
    - "{{ general.download_dir }}/{{ obj.filename }}"
  ignore_errors: true
  when: patch_exists.stat.exists and (checksum_result.stat.checksum != patch_checksum)
  tags:
    - patches

- name: "(subtask 03) downloading red hat single sign-on patch id:{{ obj.id }}"
  redhat_csp_download: 
    url: "{{ obj.url }}"
    dest: "{{ general.download_dir }}/{{ obj.filename }}"
    username: "{{ rhn_username }}"
    password: "{{ rhn_password }}"
  vars:
    debug:
      msg: "downloading {{ obj.key }} : {{ obj.id }} from: {{ obj.url }}"
  async: 600
  poll: 0
  register: patch_download_request
  no_log: true
  when: not patch_exists.stat.exists
  tags:
    - patches

- name: "(subtask 03) check on red hat single sign-on {{ rhsso_artifact_version }} patch id:{{ obj.id }} download thread"
  async_status: jid={{ patch_download_request.ansible_job_id }}
  register: jobs_result
  until: jobs_result.finished
  retries: 60
  delay: 10
  when: not patch_exists.stat.exists
  tags:
    - patches