---

- set_fact:
    obj: "{{ item }}"
  tags:
    - patches

- name: "(subtask 05) set red hat single sign on service directories facts"
  set_fact:
    jboss_eap_home: "{{ general.install_dir }}/{{ general.home_dir_name }}"
  tags:
    - patches

- name: "(subtask 05) acquire red hat single sign-on {{ rhsso_artifact_version }} directory configuration facts"
  set_fact:
    jboss_eap_bin_dir: "{{ jboss_eap_home }}/bin"
    jboss_eap_domain_home: "{{ general.install_dir }}/{{ general.home_dir_name }}/domain/configuration"
    version: "{{ obj.id }}"
  tags:
    - patches

- name: "(subtask 05) check patch history"
  command: "{{ jboss_eap_bin_dir }}/jboss-cli.sh 'patch history'"
  register: result
  changed_when: "False"
  tags:
    - patches

# problem when using with_dict because dictionaries does not sort properly, letting a later patch being applied first.
- name: "(subtask 05) applying red hat single sign-on patch id:{{ obj.id }}"
  become_user: "{{ owner.user }}"
  command: "{{ jboss_eap_bin_dir }}/jboss-cli.sh 'patch apply {{ general.download_dir }}/{{ obj.filename }} --verbose --override-all'"
  ignore_errors: true
  when: "version not in result.stdout"
  tags:
    - patches